// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(DbUruntakipContext))]
    [Migration("20240507035314_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.TblKategoriler", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("KategoriId");

                    b.ToTable("Tbl_Kategoriler");
                });

            modelBuilder.Entity("WebApplication2.Models.TblUrun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<short?>("UrunAdet")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("UrunFiyat")
                        .HasColumnType("money");

                    b.Property<string>("UrunPhoto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UrunId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Tbl_Urun");
                });

            modelBuilder.Entity("WebApplication2.Models.TblUrun", b =>
                {
                    b.HasOne("WebApplication2.Models.TblKategoriler", "TblKategoriler")
                        .WithMany("TblUruns")
                        .HasForeignKey("KategoriId");

                    b.Navigation("TblKategoriler");
                });

            modelBuilder.Entity("WebApplication2.Models.TblKategoriler", b =>
                {
                    b.Navigation("TblUruns");
                });
#pragma warning restore 612, 618
        }
    }
}
